openapi: '3.0.2'
info:
  title: Athena API
  version: '1.0'
servers:
  - url: https://localhost:3333
    description: Server description
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
