export * from './ClassScheduleRepository';
export * from './ClassroomRepository';
export * from './CourseRepository';
export * from './DisciplineRepository';
export * from './EmployeeRepository';
export * from './MatrixRepository';
export * from './PeriodRepository';
export * from './ShiftRepository';
export * from './StudentRepository';
